# KEY_LOCK_ENABLE = yes
# CONSOLE_ENABLE = no
# EXTRAFLAGS += -flto
LEADER_ENABLE = yes
WPM_ENABLE = yes
UNICODEMAP_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
MOUSEKEY_ENABLE = yes

# BOOTLOADER=qmk-dfu
# RGBLIGHT_ENABLE = yes
